name: doubletime
channels:
  - bioconda
  - conda-forge
dependencies:
  - anndata=0.10.8
  - biopython=1.84
  - bzip2=1.0.8
  - click=8.1.7
  - jinja2=3.1.4
  - networkx=3.2.1
  - pandas=1.5.3
  - pip=24.0
  - pulp=2.7.0
  - pyro-ppl=1.9.1
  - python=3.9*
  - pytorch=2.3.1
  - pyyaml=6.0.1
  - scipy=1.13.1
  - snakemake
  - tqdm=4.66.4
  - pip:
      - bamread==0.0.16
      - beautifulsoup4==4.12.3
      - bokeh==3.4.2
      - csverve==0.3.8
      - cython==0.29.37
      - dill==0.3.8
      - docutils==0.19
      - hdbscan==0.8.37
      - hmmlearn==0.3.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - matplotlib==3.9.1
      - numpy==1.23.0
      - overrides==7.7.0
      - pillow==10.4.0
      - pybigwig==0.3.23
      - pyfaidx==0.8.1.1
      - pypeliner==0.5.24
      - pyranges==0.1.2
      - pysam==0.19.0
      - scgenome==0.0.19
      - scikit-learn==1.3.2
      - seaborn==0.13.2
      - statsmodels==0.14.2
      - umap-learn==0.5.6
      - wgs-analysis==0.0.5
