name: doubletime
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - amply=0.1.6
  - anndata=0.10.8
  - appdirs=1.4.4
  - array-api-compat=1.7.1
  - async-timeout=4.0.3
  - attmap=0.13.2
  - attrs=23.2.0
  - bcrypt=4.1.3
  - biopython=1.84
  - boto3=1.34.140
  - botocore=1.34.140
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - certifi=2024.6.2
  - cffi=1.16.0
  - click=8.1.7
  - coin-or-cbc=2.10.11
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.10
  - coin-or-utils=2.11.11
  - coincbc=2.10.11
  - colorama=0.4.6
  - configargparse=1.7
  - connection_pool=0.0.3
  - cryptography=42.0.8
  - datrie=0.8.2
  - defusedxml=0.7.1
  - dpath=2.2.0
  - dropbox=12.0.2
  - eido=0.2.2
  - exceptiongroup=1.2.0
  - filechunkio=1.8
  - filelock=3.15.4
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - ftputil=5.1.0
  - gitdb=4.0.11
  - gitpython=3.1.43
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-api-core=2.19.1
  - google-api-python-client=2.136.0
  - google-auth=2.31.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.17.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.0
  - googleapis-common-protos=1.63.2
  - grpcio=1.62.2
  - h5py=3.11.0
  - hdf5=1.14.3
  - httplib2=0.22.0
  - humanfriendly=10.0
  - icu=73.2
  - idna=3.7
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - jinja2=3.1.4
  - jmespath=1.0.1
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgrpc=1.62.2
  - libhwloc=2.11.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtorch=2.3.1
  - libuuid=2.38.1
  - libuv=1.48.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - logmuse=0.2.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - natsort=8.4.0
  - nbformat=5.10.4
  - ncurses=6.5
  - networkx=3.2.1
  - oauth2client=4.1.3
  - openssl=3.3.1
  - opt_einsum=3.3.0
  - packaging=24.1
  - pandas=1.5.3
  - paramiko=3.4.0
  - peppy=0.40.2
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.3
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - ply=3.11
  - prettytable=3.10.0
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pulp=2.7.0
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pygments=2.18.0
  - pynacl=1.5.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=8.2.2
  - python=3.9.19
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-irodsclient=2.0.1
  - python-tzdata=2024.1
  - python_abi=3.9
  - pytorch=2.3.1
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - reretry=0.11.8
  - rich=13.7.1
  - rpds-py=0.18.1
  - rsa=4.9
  - s3transfer=0.10.2
  - scipy=1.13.1
  - setuptools=70.1.1
  - six=1.16.0
  - slacker=0.14.0
  - sleef=3.5.1
  - smart_open=7.0.4
  - smmap=5.0.0
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - stone=3.3.2
  - stopit=1.1.2
  - sympy=1.12.1
  - tabulate=0.9.0
  - tbb=2021.12.0
  - throttler=1.2.2
  - tk=8.6.13
  - tomli=2.0.1
  - toposort=1.10
  - tqdm=4.66.4
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ubiquerg=0.8.0
  - uritemplate=4.1.1
  - urllib3=1.26.19
  - veracitools=0.1.3
  - wcwidth=0.2.13
  - wheel=0.43.0
  - wrapt=1.16.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - yte=1.5.4
  - zipp=3.19.2
  - zstd=1.5.6
  - pip:
      - adjusttext==1.2.0
      - alabaster==0.7.16
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - babel==2.15.0
      - bamread==0.0.16
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - bokeh==3.4.2
      - brewer2mpl==1.4.1
      - charset-normalizer==2.0.12
      - comm==0.2.2
      - contourpy==1.2.1
      - csverve==0.3.8
      - cycler==0.12.1
      - cython==0.29.37
      - debugpy==1.8.2
      - decorator==5.1.1
      - dill==0.3.8
      - docutils==0.19
      - executing==2.0.1
      - fonttools==4.53.1
      - fqdn==1.5.1
      - h11==0.14.0
      - hdbscan==0.8.37
      - hmmlearn==0.3.2
      - httpcore==1.0.5
      - httpx==0.27.0
      - imagesize==1.4.1
      - importlib-metadata==8.0.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - joblib==1.1.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lda==3.0.0
      - llvmlite==0.43.0
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mypy==1.10.1
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - ncls==0.0.68
      - nest-asyncio==1.6.0
      - nose==1.3.7
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numexpr==2.10.1
      - numpy==1.23.0
      - oauthlib==3.2.2
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==0.5.6
      - pexpect==4.9.0
      - pillow==10.4.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pybigwig==0.3.23
      - pyfaidx==0.8.1.1
      - pynndescent==0.5.13
      - pypeliner==0.5.24
      - pyranges==0.1.2
      - pysam==0.19.0
      - python-json-logger==2.0.7
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - requests==2.28.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scgenome==0.0.19+11.g0dd72d5
      - scikit-learn==1.3.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sorted-nearest==0.0.39
      - soupsieve==2.5
      - sphinx==5.1.1
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tornado==6.4.1
      - types-python-dateutil==2.9.0.20240316
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wgs-analysis==0.0.5
      - widgetsnbextension==4.0.11
      - xyzservices==2024.6.0
